### ISSUE TITLE
New to docker, cannot connect to postgres when running rails test.

### ISSUE THREAD

**Issue by dwa012** [ayufan/gitlab-ci-multi-runner#30]
I am trying to get a rails test to run and it fails due to not being able to connect to the database.

I have a clean install of 14.04 with the multi runner installed via apt-get.

Here is my config.taml

```
concurrent = 1

[[runners]]
  name = "gitlab-ci-test"
  url = "https://ci.gitlab.com/"
  token = "TOKEN"
  limit = 0
  executor = "docker"
  builds_dir = ""
  clean_environment = false
  shell = ""
  disable_verbose = false
  [runners.docker]
    host = ""
    hostname = ""
    image = "ruby:2.2"
    privileged = false
    disable_cache = false
    disable_pull = false
    volumes = ["/cache"]
    cache_dir = ""
    registry = ""
    services = ["postgres:9.3"]
```

Here is the output from running the tests.

```
Starting build...
Using Docker executor with image ruby:2.2 ...
Pulling docker image postgres:9.3 ...
Starting service postgres:9.3 ...
Waiting for services to be up and running...
Running on runner-f65c0085-project-2148-concurrent-0 via vagrant-ubuntu-trusty-64...
Fetching changes...
Removing log/test.log
Checkouting b4f72b7d as master...
Reset branch 'master'

#export PATH=~/bin:/usr/local/bin:/usr/bin:/bin
#gem install bundler
bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies.......
Installing rake 10.4.0
Installing i18n 0.6.11
Using json 1.8.1
Installing minitest 5.4.3
Installing thread_safe 0.3.4
Installing tzinfo 1.2.2
Installing activesupport 4.1.8
Installing builder 3.2.2
Installing erubis 2.7.0
Installing actionview 4.1.8
Installing rack 1.5.2
Installing rack-test 0.6.2
Installing actionpack 4.1.8
Installing mime-types 2.4.3
Installing mail 2.6.3
Installing actionmailer 4.1.8
Installing activemodel 4.1.8
Installing arel 5.0.1.20140414130214
Installing activerecord 4.1.8
Using bundler 1.9.4
Installing coffee-script-source 1.8.0
Installing execjs 2.2.2
Installing coffee-script 2.3.0
Installing thor 0.19.1
Installing railties 4.1.8
Installing coffee-rails 4.0.1
Installing diff-lcs 1.2.5
Installing hike 1.2.3
Installing multi_json 1.10.1
Installing jbuilder 2.2.5
Installing jquery-rails 3.1.2
Installing libv8 3.16.14.7
Installing pg 0.17.1
Installing puma 2.9.1
Installing tilt 1.4.1
Installing sprockets 2.12.3
Installing sprockets-rails 2.2.2
Installing rails 4.1.8
Installing rails_serve_static_assets 0.0.2
Installing rails_stdout_logging 0.0.3
Installing rails_12factor 0.0.3
Installing rdoc 4.1.2
Installing ref 1.0.5
Installing rspec-support 3.2.2
Installing rspec-core 3.2.3
Installing rspec-expectations 3.2.1
Installing rspec-mocks 3.2.1
Installing rspec-rails 3.2.1
Installing sass 3.2.19
Installing sass-rails 4.0.5
Installing sdoc 0.4.1
Installing spring 1.2.0
Installing therubyracer 0.12.2
Installing turbolinks 2.5.2
Installing uglifier 2.5.3
Bundle complete! 14 Gemfile dependencies, 55 gems now installed.
Bundled gems are installed into /usr/local/bundle.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
RAILS_ENV=test bundle exec rake db:setup
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `new'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:8:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:17:in `create'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:88:in `create'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:102:in `block in create_current'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:101:in `create_current'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:240:in `call'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:235:in `each'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:235:in `execute'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:199:in `each'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:199:in `each'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/task.rb:165:in `invoke'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:156:in `invoke_task'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:112:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:112:in `each'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:112:in `block in top_level'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:121:in `run_with_threads'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:106:in `top_level'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:84:in `block in run'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:182:in `standard_exception_handling'
/usr/local/bundle/gems/rake-10.4.0/lib/rake/application.rb:79:in `run'
/usr/local/bundle/gems/rake-10.4.0/bin/rake:33:in `<top (required)>'
/usr/local/bundle/bin/rake:16:in `load'
/usr/local/bundle/bin/rake:16:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>"postgres", "timeout"=>5000, "database"=>"postgres", "password"=>nil}
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `new'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `connect'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:8:in `connection'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:30:in `drop'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/postgresql_database_tasks.rb:43:in `purge'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:144:in `purge'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:170:in `load_schema_for'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:185:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:225:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:224:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/tasks/database_tasks.rb:184:in `load_schema_current'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-4.1.8/lib/active_record/railties/databases.rake:242:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)

Build failed with exit code 1
```
Any help with getting postgres ready and able to connect would be awesome.

**Comment by ayufan** [comment]
Connect to hostname: `postgres`. Something like that should do the work:

```
cp config/database.yml.postgresql config/database.yml
sed -i 's/username:.*/username: postgres/g' config/database.yml
sed -i 's/password:.*/password:/g' config/database.yml
sed -i 's/# socket:.*/host: postgres/g' config/database.yml```

**Comment by dwa012** [comment]
@ayufan That was the trick, just had to specify the host.

Here is my example database config for the test section for reference.

```
  database: test_database
  username: postgres 
  password: password
  host: postgres
```

**Comment by ayufan** [comment]
I guess it's not clarified in docks that databases (and any service) is exposed under hostname (not on localhost).

**Comment by dwa012** [comment]
That is what was tripping me up, even the postgres docker docs were not clear on where is was exposed.
